SELECT * FROM employee WHERE ENAME LIKE 'M%';
SELECT * FROM employee WHERE JOB='MANAGER';
SELECT * FROM employee WHERE SAL>1500;
SELECT ENAME, JOB FROM employee WHERE COMM IS NOT NULL;
SELECT UNIQUE JOB FROM employee ;
UPDATE employee SET SAL=SAL+300 WHERE JOB='SALESMAN';
SELECT ENAME FROM employee WHERE MGR IS NULL;
CREATE TABLE DEPT_30_EMP AS (SELECT * FROM employee WHERE DEPTNO=30);
ALTER TABLE employee RENAME COLUMN JOB TO DESIG;
SELECT SUM(SAL)"TOT_EARINING" FROM employee;
UPDATE employee SET DESIG='MANAGER' WHERE EMPNO=7521;

SELECT NAME FROM students WHERE CGPA>6.5 and CGPA<=9;
SELECT NAME FROM students WHERE CITY!='Kolkota';
ALTER TABLE students ADD EMAIL VARCHAR(100);
UPDATE students SET CGPA=9.5 WHERE ROLL=1905103 OR ROLL=1905105 OR ROLL=1905211;