/* 1 */
SELECT SUM(STRENGTH), CATEGORY FROM DEPARTMENT GROUP BY CATEGORY;

/* 2 */
SELECT CATEGORY FROM (SELECT SUM(STRENGTH) AS SUM_S, CATEGORY FROM DEPARTMENT GROUP BY CATEGORY ORDER BY SUM_S DESC) WHERE ROWNUM <= 1;

/* 3 */
ALTER TABLE employee ADD SALARY number(5) DEFAULT 0;

/* 4 */
UPDATE employee SET SALARY = dbms_random.value(5000,12000);

/* 5 */
SELECT AVG(SALARY), DEPTNO FROM EMPLOYEE GROUP BY DEPTNO;  

/* 6 */
SELECT MAX(SALARY), DEPTNO FROM EMPLOYEE GROUP BY DEPTNO;

/* 7 */
SELECT AVG_S, DEPTNO FROM (SELECT AVG(SALARY) AS AVG_S, DEPTNO FROM EMPLOYEE GROUP BY DEPTNO ORDER BY AVG_S DESC) WHERE ROWNUM <=1;